### ISSUE TITLE
Use SVGO?

### ISSUE THREAD

**Issue by adunkman** [js-kyle/connect-assets#253]
I don’t know much about it, but there’s an SVG optimizer called [SVGO](https://github.com/svg/svgo) that uses node.js. It might be cool to support using it to compress SVGs on the fly?

If this is a thing that we’d want, it’d probably be in [mincer](https://github.com/nodeca/mincer) first, then we’d update to use it here.

**Comment by netsgnut** [comment]
Interesting idea. Although I guess we will have to reference how Mincer should do it.

Ref: https://github.com/nodeca/mincer/issues/181
