### ISSUE TITLE
require paths not cross platform

### ISSUE THREAD

**Issue by technomage** [js-kyle/connect-assets#273]
Currently the use of relative paths for //= require results in non cross platform source files.  For example if in application.js (the root file) you require_tree package then in package you try to define local dependencies within that package so the tree loads in proper order, those references must be relative and thus have a path separator.  This requires the source files to be either unix of windows but can not function on both.  it would be best if the require path was split on '/' and then joined using path.join to accommodate running on different systems.

**Comment by blakevanlan** [comment]
This is a bug in `mincer` that we should work to resolve.
