### ISSUE TITLE
"buildDir" config option ... absolute path does not work

### ISSUE THREAD

**Issue by iamjochem** [js-kyle/connect-assets#279]
I cannot get my head round the fact that buildDir only works if the value is a relative path - forcing the buildDir to be configured as a path relative to the current working directory is a PITA  for anyone who uses some kind of supervisor/init daemon to run their apps in production, and even during development it's a bit of a stretch to assume someones CWD is always going to be the root of the 'current' project. 

I'm currently doing the following (somewhere in my app) to work around the problem (and make the buildDir location deterministic), this is hardly ideal IMO:

``` js
process.chdir(__dirname + '/../');
```

please make it possible to use absolute paths (or if it is an upstream problem related to Mincer then add a little something to the README so the next person to potentially run into this gets a head ups before hand)

PS - I did find the very old closed issues about this problem - but since it's not possible (for me) to re-open them, I had to create a new issue ... sorry for adding to your list!

**Comment by hsablonniere** [comment]
A better way until it's fixed is to provide a path relative to process current working directory.

```javascript
var absoluteBuildDir = path.join(__dirname, '..'),
    relativeBuildDir = path.relative(process.cwd(), absoluteBuildDir);

app.use(assets({
    buildDir: relativeBuildDir
}));
```

**Comment by blakevanlan** [comment]
This is rough. Definitely need to get it fixed.

**Comment by iaincollins** [comment]
if it helps, I think thought I got round this by specifying a double slash at the beginning at some point (e.g. "//tmp/foo/bar") but I'm not sure why that worked or if it's cross platform or just a quirk.
