### ISSUE TITLE
Append assets to manifest using `asset_path`

### ISSUE THREAD

**Issue by sebastianhoitz** [js-kyle/connect-assets#301]
I have the following scenario:

I have an angularJS app that contains some directives that reference additional html files.

This is the way I'm using the asset_path helper right now:

``` coffeescript
Directive = ($http, RecursionHelper) ->
  directive =
    restrict: "E"
    templateUrl: '"$$ asset_path("app/directives/attribute.html") $$"'
```

However, when compiling the assets, the html file is not added to the manifest and can thus not be accessed from my client. I have to manually add every html file to the list of files that I want to compile.

Question: Why can't asset_path do this automatically?

**Comment by blakevanlan** [comment]
Sorry I know this has been here forever, but how would you expect this to work? How would connect-assets know of the dependency at compile time?
