### ISSUE TITLE
buildDir: "./path" does not honor fingerprint: false

### ISSUE THREAD

**Issue by tomas** [js-kyle/connect-assets#311]
I'm on 4.7.1 and the assets get built but including fingerprints. I want to be able to build them using their original files (eg. application.js instead of application-abcdef123456.js).

**Comment by blakevanlan** [comment]
Conceivably you could write a script to remove the fingerprints from each file, but I know that's a pain. I'll look into adding an option for this.

**Comment by blakevanlan** [comment]
This would actually need to be done in mincer.
