### ISSUE TITLE
[SafetyColons] Cannot read property 'trimRight' of undefined when using 5.4.0

### ISSUE THREAD

**Issue by benzen** [js-kyle/connect-assets#352]
This error message happens when serving an app build with coffeescript

**Comment by benzen** [comment]
And it did not happens when using 4.8.0

**Comment by fxg42** [comment]
@benzen Seems to be related to how Mincer handles the output from the coffee-script engine when sourcemaps are enabled. Initializing the connect-assets environment with `{ sourceMaps: false }` bypasses the (possibly) faulty behaviour.
